apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
      app: auth
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
        app: auth
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust

